apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  annotations: {}
  labels:
    name: psp-openshift-restricted
  name: psp:openshift-restricted
rules:
- apiGroups:
  - policy
  resourceNames:
  - 32-openshift-restricted
  resources:
  - podsecuritypolicies
  verbs:
  - use

