apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  annotations: {}
  labels:
    name: psp-nonroot
  name: psp:nonroot
rules:
- apiGroups:
  - policy
  resourceNames:
  - 40-nonroot
  resources:
  - podsecuritypolicies
  verbs:
  - use

