---
apiVersion: v1
kind: Namespace
metadata:
  name: test-simple
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-simple-sa
  namespace: test-simple
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
  name: edit
  namespace: test-simple
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: test-simple-sa
  namespace: test-simple
